### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by ymnliu** [OHNLP/UIMA-Stream-Server#2]
> The resulting executable `./UIMA-Server-REST/target/UIMA-Server-Core-1.0-SNAPSHOT.jar` can be directly run via `java -jar <JVM_ARGS> UIMA-Server-Core-1.0-SNAPSHOT.jar` alongside the appropriate JVM_ARGS as desired

Can you verify the two paths? 

- The `UIMA-Server-Core-1.0-SNAPSHOT.jar` is under `./UIMA-Server-Core/target` rather than `./UIMA-Server-REST/target/`, and it cannot run alone.
- The `UIMA-REST-SERVER.jar` is under `UIMA-Server-REST/target`, and running the `UIMA-REST-SERVER.jar` will throw the issue below:

```
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at edu.mayo.dhs.uima.server.core.UIMAServerBase.<init>(UIMAServerBase.java:38) ~[UIMA-REST-SERVER.jar:1.0-SNAPSHOT]
	at edu.mayo.dhs.uima.server.rest.UIMARESTServer.<init>(UIMARESTServer.java:29) ~[UIMA-REST-SERVER.jar:1.0-SNAPSHOT]
	at edu.mayo.dhs.uima.server.rest.UIMARESTServer$$EnhancerBySpringCGLIB$$8ac82b0c.<init>(<generated>) ~[UIMA-REST-SERVER.jar:1.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[UIMA-REST-SERVER.jar:1.0-SNAPSHOT]
	... 20 common frames omitted
```

**Comment by qqndrew** [comment]
It's the second UIMA-REST-SERVER.jar. Have updated documentation accordingly.

Your second issue is due to system classloader changes in java9+. This error will not occur in JRE8.

Will investigate implementing a workaround using jvm version checking...

**Comment by ymnliu** [comment]
Downgrading Java to 8 resolves the issue.
